/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Aws(props) {
  const { nodes, materials } = useGLTF("/aws.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.5, 1.495, 0]}
        rotation={[Math.PI, 0, 0]}
        scale={[0.02, 0.02, 0.25]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_4.geometry}
          material={nodes.mesh_4.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/aws.gltf");
