/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cogman-art (https://sketchfab.com/cogman-art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ajolote-de-minecraft-unico-4a388e4faf094d82adb31e956fcffa00
Title: ajolote de minecraft unico
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import * as THREE from "three";
import gsap from "gsap";

const colors = [
  "rgb(255,195,211)",
  "rgb(241,154,179)",
  "rgb(219,154,176)",
  "rgb(255,224,249)",
  "rgb(255,117,173)",
  "rgb(233,186,202)",
  "rgb(18,0,59)",
  "rgb(255,132,182)",
  "rgb(219,177,201)",
  "rgb(255,137,160)",
  "rgb(223,71,114)",
  "rgb(218,173,182)",
  "rgb(209,59,105)",
  "rgb(219,108,142)",
  "rgb(255,110,182)",
  "rgb(255,146,172)",
  "rgb(255,168,198)",
  "rgb(255,0,80)",
  "rgb(231,77,161)",
  "rgb(240,106,204)",
  "rgb(255,143,213)",
  "rgb(255,189,213)",
  "rgb(240,134,159)",
  "rgb(231,128,98)",
  "rgb(231,59,86)",
  "rgb(255,46,113)",
  "rgb(255,151,191)",
  "rgb(255,100,160)",
  "rgb(231,231,231)",
];

// colores morados que seran para sustituir los colores del modelo segun el array anterior
const purpleMatches = [
  "rgb(217,195,255)", // match suave y pastel
  "rgb(191,154,241)", // similar saturación
  "rgb(188,154,219)", // tono malva
  "rgb(230,215,255)", // pastel lavanda
  "rgb(202,117,255)", // violeta fuerte
  "rgb(203,186,233)", // lavanda claro
  "rgb(55,0,105)", // morado profundo (match con el azul oscuro)
  "rgb(209,132,255)", // tono lila intenso
  "rgb(199,177,219)", // lavanda suave
  "rgb(215,137,255)", // lila vibrante
  "rgb(173,71,223)", // violeta magenta
  "rgb(204,173,218)", // lavanda grisáceo
  "rgb(155,59,209)", // violeta fuerte
  "rgb(181,108,219)", // tono intermedio
  "rgb(215,110,255)", // magenta violeta
  "rgb(222,146,255)", // tono dulce y suave
  "rgb(228,168,255)", // lila pastel
  "rgb(180,0,255)", // violeta puro
  "rgb(201,77,231)", // púrpura rosado
  "rgb(196,106,240)", // violeta vivo
  "rgb(225,143,255)", // tono nube púrpura
  "rgb(232,189,255)", // lavanda suave
  "rgb(206,134,240)", // violeta coralino
  "rgb(160,128,231)", // lila grisáceo
  "rgb(180,59,231)", // violeta eléctrico
  "rgb(210,46,255)", // match brillante
  "rgb(237,151,255)", // tono caramelo violeta
  "rgb(201,100,255)", // púrpura fuerte
  "rgb(200,200,255)", // gris azulado con violeta
];
const darkPurpleMatches = [
  "rgb(145,105,180)", // versión oscura pastel
  "rgb(120,60,160)", // ciruela profundo
  "rgb(110,65,140)", // malva oscuro
  "rgb(150,120,190)", // lavanda grisáceo
  "rgb(135,40,170)", // violeta intenso
  "rgb(100,70,120)", // morado frío apagado
  "rgb(10,0,35)", // morado casi negro
  "rgb(130,60,170)", // lila fuerte oscuro
  "rgb(120,90,150)", // lavanda vintage
  "rgb(140,70,180)", // violeta dramático
  "rgb(115,40,160)", // púrpura profundo
  "rgb(130,100,140)", // gris morado suave
  "rgb(105,30,150)", // uva madura
  "rgb(115,55,155)", // orquídea oscura
  "rgb(130,50,175)", // magenta púrpura
  "rgb(140,80,160)", // tono vino lila
  "rgb(160,90,180)", // púrpura terciopelo
  "rgb(110,0,130)", // violeta nocturno
  "rgb(125,40,145)", // morado sofisticado
  "rgb(115,50,170)", // morado ciruela
  "rgb(145,60,180)", // tono galaxia
  "rgb(155,100,175)", // violeta opaco
  "rgb(135,70,160)", // lila denso
  "rgb(100,60,145)", // berenjena claro
  "rgb(120,35,160)", // violeta eléctrico oscuro
  "rgb(135,30,170)", // acento neón púrpura
  "rgb(155,65,170)", // uva brillante
  "rgb(115,40,160)", // púrpura sólido
  "rgb(90,90,140)", // azul morado profundo
];

export function Axolote(props) {
  const { nodes, materials } = useGLTF(
    "/ajolote_de_minecraft_unico/scene.gltf"
  );

  const eyesRef = useRef();
  const mouthRef = useRef();
  const bodyRef = useRef();
  //tween gsap
  const eyesTween = useRef();
  const mouthTween = useRef();
  const bodyTween = useRef();
  const animateAxoloteColorsTl = useRef();

  const handleHover = (event) => {
    eyesTween.current.play(); // Play the tween animation for eyes
    mouthTween.current.play(); // Play the tween animation for mouth
    bodyTween.current.play(); // Play the tween animation for body
    // animateAxoloteColorsTl.current.play(); // Play the color animation timeline
  };
  const handleUnhover = (event) => {
    eyesTween.current.reverse(); // Reverse the tween animation for eyes
    mouthTween.current.reverse(); // Reverse the tween animation for mouth
    bodyTween.current.reverse(); // Reverse the tween animation for body
    // animateAxoloteColorsTl.current.reverse(); // Reverse the color animation timeline
  };

  useEffect(() => {
    // Tween the eyes and mouth colors when the component mounts
    if (eyesRef.current && mouthRef.current) {
      eyesTween.current = gsap
        .to(eyesRef.current.scale, {
          z: 1.5,
          duration: 0.5,
          ease: "power1.inOut",
        })
        .pause(); // Pause the tween initially
      mouthTween.current = gsap
        .to(mouthRef.current.scale, {
          x: 1.2,
          z: 1.2,
          duration: 0.5,
          ease: "power1.inOut",
        })
        .pause(); // Pause the tween initially
      bodyTween.current = gsap
        .to(bodyRef.current.scale, {
          y: bodyRef.current.scale.y * 1.2,
          z: bodyRef.current.scale.z * 1.2,
          x: bodyRef.current.scale.x * 1.2,
          duration: 0.5,
          ease: "power1.inOut",
        })
        .pause(); // Pause the tween initially

      // animar colores entre los colores del morados y los colores morados oscuros
      animateAxoloteColorsTl.current = gsap.timeline({ paused: true });
      animateAxoloteColorsTl.current.add(
        gsap.to(materials, {
          duration: 1,
          ease: "power1.inOut",
          onUpdate: () => {
            for (const material in materials) {
              if (materials[material].color) {
                // Check if the material color is in the colors array
                const index = colors.indexOf(
                  materials[material].color.getStyle()
                );
                if (index !== -1) {
                  // If it is, set the color to the corresponding purple color
                  materials[material].color.set(purpleMatches[index]);
                } else {
                  // If not, set a default purple color
                  materials[material].color.set("rgb(128,0,128)");
                }
              }
            }
          },
        })
      );
      animateAxoloteColorsTl.current.pause(); // Pause the timeline initially
    }
  }, [eyesRef, mouthRef]);

  useEffect(() => {
    for (const material in materials) {
      if (materials[material].color) {
        // Check if the material color is in the colors array
        const index = colors.indexOf(materials[material].color.getStyle());
        if (index !== -1) {
          // If it is, set the color to the corresponding purple color
          materials[material].color.set(darkPurpleMatches[index]);
        } else {
          // If not, set a default purple color
          materials[material].color.set("rgb(128,0,128)");
        }
      }
    }
  }, [materials]);

  const { posX, posY, posZ, scale, rotationX, rotationY, rotationZ } =
    useControls("Axolote", {
      posX: {
        value: 0.3,
        label: "Position X",
        min: -10,
        max: 10,
        step: 0.1,
      },
      posY: {
        value: -1.7,
        label: "Position Y",
        min: -10,
        max: 10,
        step: 0.1,
      },
      posZ: {
        value: -3.3,
        label: "Position Z",
        min: -10,
        max: 10,
        step: 0.1,
      },
      scale: {
        value: 1.6,
        label: "Scale X",
        min: 0.1,
        max: 5,
        step: 0.1,
      },

      rotationX: {
        value: 0,
        label: "Rotation X",
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
      },
      rotationY: {
        value: -2.4,
        label: "Rotation Y",
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
      },
      rotationZ: {
        value: 0,
        label: "Rotation Z",
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
      },
    });
  return (
    <group
      {...props}
      dispose={null}
      position={[posX, posY, posZ]}
      scale={scale}
      rotation={[rotationX, rotationY, rotationZ]}
      onPointerEnter={handleHover}
      onPointerLeave={handleUnhover}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.159}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[1441.128, 1350.43, -1047.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[108.997, 172.399, 88.631]}
            ref={bodyRef}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_1003_0.geometry}
              material={materials["1.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_5_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_Material032_0.geometry}
              material={materials["Material.032"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_8_0.geometry}
              material={materials.material_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_4_0.geometry}
              material={materials.material_4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_11_0.geometry}
              material={materials.material_5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_2_0.geometry}
              material={materials.material_6}
              ref={eyesRef}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_3_0.geometry}
              material={materials.material_7}
              ref={mouthRef}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_12_0.geometry}
              material={materials.material_8}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_9_0.geometry}
              material={materials.material_9}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_Material033_0.geometry}
              material={materials["Material.033"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo008_7_0.geometry}
              material={materials.material_11}
            />
          </group>
          <group
            position={[1142.792, 1336.045, -1065.667]}
            rotation={[-Math.PI / 2, 0, 1.568]}
            scale={[153.853, 188.924, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material012_0.geometry}
              material={materials["Material.012"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material034_0.geometry}
              material={materials["Material.034"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material035_0.geometry}
              material={materials["Material.035"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material015_0.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material014_0.geometry}
              material={materials["Material.014"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material017_0.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material016_0.geometry}
              material={materials["Material.016"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material018_0.geometry}
              material={materials["Material.018"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material019_0.geometry}
              material={materials["Material.019"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material020_0.geometry}
              material={materials["Material.020"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo015_Material021_0.geometry}
              material={materials["Material.021"]}
            />
          </group>
          <group
            position={[748.599, 1350.807, -1047.95]}
            rotation={[3.141, 0, 1.571]}
            scale={[-86.244, 205.557, 17.73]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo016_Material013_0.geometry}
              material={materials["Material.013"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo016_Material031_0.geometry}
              material={materials["Material.031"]}
            />
          </group>
          <group
            position={[1285.661, 1246.363, -1385.122]}
            rotation={[2.826, 0, 1.57]}
            scale={[156.653, 188.924, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo017_Material026_0.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo017_Material023_0.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo017_Material024_0.geometry}
              material={materials["Material.024"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo017_Material025_0.geometry}
              material={materials["Material.025"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo017_Material022_0.geometry}
              material={materials["Material.022"]}
            />
          </group>
          <group
            position={[1375.571, 1441.743, -1281.922]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[156.653, 207.609, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo018_Material006_0.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo018_Material008_0.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo018_Material007_0.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group
            position={[1375.535, 1313.002, -1289.585]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[156.653, 207.609, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo019_Material009_0.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo019_Material010_0.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo019_Material011_0.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[1362.187, 1495.081, -1162.774]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[156.653, 207.609, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo020_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo020_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo020_Material005_0.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group
            position={[857.027, 1361.899, -1046.961]}
            rotation={[3.141, 0, 1.571]}
            scale={[-86.244, 205.557, 12.73]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo021_Material030_0.geometry}
              material={materials["Material.030"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo021_Material029_0.geometry}
              material={materials["Material.029"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo021_Material028_0.geometry}
              material={materials["Material.028"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo021_Material027_0.geometry}
              material={materials["Material.027"]}
            />
          </group>
          <group
            position={[1387.779, 1495.113, -934.931]}
            rotation={[-Math.PI / 2, 0, -3.139]}
            scale={[156.653, 207.609, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo022_Material003_0.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo022_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo022_Material005_0.geometry}
              material={materials["Material.005"]}
            />
          </group>
          <group
            position={[1374.724, 1442.402, -812.803]}
            rotation={[-Math.PI / 2, 0, -3.136]}
            scale={[156.653, 207.608, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo023_Material006_0.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo023_Material008_0.geometry}
              material={materials["Material.008"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo023_Material007_0.geometry}
              material={materials["Material.007"]}
            />
          </group>
          <group
            position={[1374.645, 1313.048, -806.051]}
            rotation={[-Math.PI / 2, 0, -3.137]}
            scale={[156.653, 207.608, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo024_Material009_0.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo024_Material010_0.geometry}
              material={materials["Material.010"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo024_Material011_0.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[1020.361, 1246.363, -1385.122]}
            rotation={[2.826, 0, 1.57]}
            scale={[156.653, 188.924, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo025_Material026_0.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo025_Material023_0.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo025_Material024_0.geometry}
              material={materials["Material.024"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo025_Material025_0.geometry}
              material={materials["Material.025"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo025_Material022_0.geometry}
              material={materials["Material.022"]}
            />
          </group>
          <group
            position={[1009.553, 1240.739, -792.719]}
            rotation={[0.315, -0.009, -1.569]}
            scale={[156.653, 188.924, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo026_Material026_0.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo026_Material023_0.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo026_Material024_0.geometry}
              material={materials["Material.024"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo026_Material025_0.geometry}
              material={materials["Material.025"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo026_Material022_0.geometry}
              material={materials["Material.022"]}
            />
          </group>
          <group
            position={[1275.194, 1240.481, -792.719]}
            rotation={[0.315, -0.009, -1.569]}
            scale={[156.653, 188.924, 71.441]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo027_Material026_0.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo027_Material023_0.geometry}
              material={materials["Material.023"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo027_Material024_0.geometry}
              material={materials["Material.024"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo027_Material025_0.geometry}
              material={materials["Material.025"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cubo027_Material022_0.geometry}
              material={materials["Material.022"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ajolote_de_minecraft_unico/scene.gltf");
